import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import iconImage from "../../public/favicon/main logo.png";

import { GoogleOAuthProvider } from "@react-oauth/google";
import Provider from "@/context/emailContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BookHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? "";

  return (
    <html lang="en">
      <GoogleOAuthProvider clientId={clientId}>
        <link rel="icon" href={iconImage.src} sizes="any" />
        <body className={inter.className}>
          <Provider>{children}</Provider>
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
